// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package webwrap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReactRendererClient is the client API for ReactRenderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReactRendererClient interface {
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type reactRendererClient struct {
	cc grpc.ClientConnInterface
}

func NewReactRendererClient(cc grpc.ClientConnInterface) ReactRendererClient {
	return &reactRendererClient{cc}
}

func (c *reactRendererClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, "/main.ReactRenderer/Render", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactRendererServer is the server API for ReactRenderer service.
// All implementations must embed UnimplementedReactRendererServer
// for forward compatibility
type ReactRendererServer interface {
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	mustEmbedUnimplementedReactRendererServer()
}

// UnimplementedReactRendererServer must be embedded to have forward compatible implementations.
type UnimplementedReactRendererServer struct {
}

func (UnimplementedReactRendererServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedReactRendererServer) mustEmbedUnimplementedReactRendererServer() {}

// UnsafeReactRendererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReactRendererServer will
// result in compilation errors.
type UnsafeReactRendererServer interface {
	mustEmbedUnimplementedReactRendererServer()
}

func RegisterReactRendererServer(s grpc.ServiceRegistrar, srv ReactRendererServer) {
	s.RegisterService(&ReactRenderer_ServiceDesc, srv)
}

func _ReactRenderer_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactRendererServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ReactRenderer/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactRendererServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReactRenderer_ServiceDesc is the grpc.ServiceDesc for ReactRenderer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReactRenderer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.ReactRenderer",
	HandlerType: (*ReactRendererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _ReactRenderer_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/com.proto",
}
