
name: verify website
on: 
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  integration_tests:
    name: verify website
    runs-on: ubuntu-latest
    container: ghcr.io/guyaross/orbit-tooling:v2
    steps:
      - uses: actions/checkout@v2
      - run: |          
          python3 ./scripts/verify_website.py
